### ISSUE TITLE
[discuss] update plugin keywords

### ISSUE THREAD

**Issue by Zeroto521** [Flow-Launcher/Flow.Launcher.PluginsManifest#1]
https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/blob/497a2596876171cb5891f4640239c7a7218ea88e/plugins.json#L3-L5

Should we use more keywords?

The following contents are `plugin.json`.

```JSON
{
  "ID": "D2D2C23B084D411DB66FE0C79D6C2A6E",
  "ActionKeyword": "*",
  "Name": "Everything",
  "Description": "Search Everything",
  "Author": "qianlifeng,orzfly",
  "Version": "1.1.2",
  "Language": "csharp",
  "Website": "https://github.com/Flow-Launcher/Flow.Launcher",
  "IcoPath": "Images\\find.png",
  "ExecuteFileName": "Flow.Launcher.Plugin.Everything.dll",
  "Disabled": false
}
```

`name`, `version`, and `url` keywords are too few.

I think some other keywords need for that. 

- `ID`: It can be clear different plugins. It is **necessary**.
- `Description`: It also needs.
- `Author`: It would need.
- `website`: It is the plugin homepage link. It is **necessary**. I think it needs to change to another name called `homepage` or else.
- `url`: I think this should change another name. It is called `downloadURL`. So it can distinguish `website`.
- `name` & `version` just keep.

---

We could build an online plugin service via this file.

And we should write a guide on how to make a standard to build flow plugin.

**Comment by jjw24** [comment]
yep definitely. I am adding them as i build the new plugin manager

**Comment by jjw24** [comment]
done. pretty much everything in the plugin.json except for actionkeywords. added UrlDownload and UrlSourceCode if the Website is hosted somewhere different to SourceCode location
