### ISSUE TITLE
Update test python plugin ci to find python plugin that does not have tested field

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher.PluginsManifest#141]
Update test python plugin ci to find python plugin that does not have tested field- current method only checks the last plugin to see if it is python. This might not work if there is more than one submission or if the new plugin is not in the last entry (e.g. from resolving main branch conflict).

**Comment by Garulf** [comment]
I actually have this fixed in a branch. Just havent tested it enough to make sure it's ready for deployment.
