### ISSUE TITLE
Last publish release action is not included in the manifest

### ISSUE THREAD

**Issue by danielduckworth** [Flow-Launcher/Flow.Launcher.PluginsManifest#157]
Hey @jjw24 found a bug in the notion search plugin. It was difficult to test the plugin in dev because it can't call the main FlowLauncher class. I ended up doing testing by editing the code in the app's plugin folder.

I pushed the fix and v0.1.5 is the last release. But the manifest still says 0.1.4. Is there anything else I need to do?

https://github.com/danielduckworth/Flow.Launcher.Plugin.NotionSearch

Thanks,
Daniel.

**Comment by Garulf** [comment]
That's because the plugin manifest  repository automatically updates on a schedule of every 3 hours. 

I can see it has updated now though.
