### ISSUE TITLE
Is it safe to store the password in the Flow.Launcher?

### ISSUE THREAD

**Issue by vladislav-atakhanov** [Flow-Launcher/Flow.Launcher.PluginsManifest#201]
I want to make a database connection plugin. How can I store the password from this database?
It's good if I can store it in the Flow.Launcher so that you can easily change it. Is it safe?

**Comment by Garulf** [comment]
If you’re concerned about security you may want to look into https://learn.microsoft.com/en-us/windows/uwp/security/credential-locker

**Comment by vladislav-atakhanov** [comment]
Thx
