### ISSUE TITLE
Installed number

### ISSUE THREAD

**Issue by asmpro7** [Flow-Launcher/Flow.Launcher.PluginsManifest#238]
as a developer, It will be very good to know how many people install my plugins, so can you add it plugin store under the plugin name and description?

**Comment by Garulf** [comment]
Since Flow Launcher downloads from your repo when a user installed your plugin you can track this with GitHub's api. 

One way to access it is with: https://tooomm.github.io/github-release-stats/

**Comment by asmpro7** [comment]
> Since Flow Launcher downloads from your repo when a user installs your plugin you can track this with GitHub's api.
> 
> One way to access it is with: https://tooomm.github.io/github-release-stats/

yes, I know so I make simple code to get all plugins and their download 
[DownCount.zip](https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/files/11471037/DownCount.zip)
but there is a small problem with it: API rate limit

**Comment by asmpro7** [comment]
![image](https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/assets/114514662/43edef61-6dcf-4e1b-aaae-ecfcdccc38c1)
the site uses the same way too and faces the same problem 😢

**Comment by Garulf** [comment]
Are you using an API token? This should increase the rate limit a little if I'm not mistaken.
