### ISSUE TITLE
Auto Update CI do not update plugin version

### ISSUE THREAD

**Issue by KrystianLesniak** [Flow-Launcher/Flow.Launcher.PluginsManifest#267]
**Issue Description:**
Yesterday (about 24 hours ago) I have published new release of a plugin (in version 1.2.0) to my repository. Plugin entry is present in `plugins.json` file. For some reason CI Auto Updater that is executed every 3 hours is not increasing initial version from 1.1.0 to 1.2.0.

**Affected Repository:** 
https://github.com/KrystianLesniak/Flow.Launcher.Plugin.GamesLauncher
```
    {
        "ID": "54545DC7B3A542DBB6C7DA50DEAD455B",
        "Name": "GamesLauncher",
        "Description": "Search and launch games from multiple platforms like Steam, Epic Games etc.",
        "Author": "KrystianLesniak",
        "Version": "1.1.0",
        "Language": "csharp",
        "Website": "https://github.com/KrystianLesniak/Flow.Launcher.Plugin.GamesLauncher",
        "UrlDownload": "https://github.com/KrystianLesniak/Flow.Launcher.Plugin.GamesLauncher/releases/download/v1.1.0/GamesLauncher.zip",
        "UrlSourceCode": "https://github.com/KrystianLesniak/Flow.Launcher.Plugin.GamesLauncher/tree/main",
        "IcoPath": "https://cdn.jsdelivr.net/gh/krystianlesniak/Flow.Launcher.Plugin.GamesLauncher@master/Flow.Launcher.Plugin.GamesLauncher/icon.png",
        "DateAdded": "2023-08-22T14:44:38Z",
        "LatestReleaseDate": null
    }
```
Repository have tags in this format: "v1.0.0", "v1.1.0", "v1.2.0"
Release titles are: "v1.0.0", "v1.1.0", "v1.2.0"
Attached zip with binaries is without version suffix - "GamesLauncher.zip" instead of for example "GamesLauncher-1.2.0.zip".

**Additional Context:**
It's very unlikely as the source of issue but initial entry in plugins.json was made with version 1.1.0 instead of 1.0.0.

**Summary:**
The custom Continuous Integration (CI) system in repository is designed to automatically update information about plugins every 3 hours, but it has not updated my plugin information for the past 24 hours.

Thank you for your attention to this issue. Please let me know if you need any further information or assistance in resolving this issue. I would be happy to help as much as I can, I have tried to investigate issue myself but I am not really expertise in Python language.

**Comment by jjw24** [comment]
Hi there, I think the issue could be our end with the autoupdater workflow action failing silently. I will try to take a look soon.
