### ISSUE TITLE
I created a plugin but cannot add this to the plugins.json file

### ISSUE THREAD

**Issue by RrobertRr** [Flow-Launcher/Flow.Launcher.PluginsManifest#297]
my steps:
1. clone of repo
2. create a local branch
3. update the plugins.json file
4. push local branch to remote => Failed!!! => no permission.

How are the steps to update the plugins.json file with my plugin?

**Comment by Garulf** [comment]
When you say "push local branch to remote" are you pushing to your forked repository?

If you're trying to push to the original repository you have to create a Pull Request.

See here for more info: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by RrobertRr** [comment]
Thank you. 
I cloned the original repo.
Now I created a fork of this repo and created a pull request from the fork.

Thank you.
