### ISSUE TITLE
Enhance: Add CI to autoly check PR

### ISSUE THREAD

**Issue by Zeroto521** [Flow-Launcher/Flow.Launcher.PluginsManifest#3]
As title.

And I will do some try on my fork

**Comment by jjw24** [comment]
Only auto merge once pr is approved please

**Comment by Zeroto521** [comment]
Fine, just do check work no merge work

**Comment by jjw24** [comment]
I mean it can be auto merged, but just need to ensure that the pr is in the approved status, not sure if the Action will honor protected branch setting

**Comment by Zeroto521** [comment]
[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBTdGFydCAtLT4gUFJbQSBuZXcgUFJdXG4gICAgUFIgLS0-IENJWy9DSSBXb3JrL11cbiAgICBDSSAtLT4gZmxhZ3tQYXNzZWR9XG4gICAgZmxhZyAtLT4gfFllc3wgYXBwcm92ZWRbQXBwcm92ZWQgc3RhdHVzXVxuICAgIGFwcHJvdmVkIC0tPiB8V2hvfCBNZXJnZVtQUiBtZXJnZWQgdG8gbWFzdGVyXVxuICAgIFxuICAgIGZsYWcgLS0-IHxOb3wgQmxvY2tcbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBTdGFydCAtLT4gUFJbQSBuZXcgUFJdXG4gICAgUFIgLS0-IENJWy9DSSBXb3JrL11cbiAgICBDSSAtLT4gZmxhZ3tQYXNzZWR9XG4gICAgZmxhZyAtLT4gfFllc3wgYXBwcm92ZWRbQXBwcm92ZWQgc3RhdHVzXVxuICAgIGFwcHJvdmVkIC0tPiB8V2hvfCBNZXJnZVtQUiBtZXJnZWQgdG8gbWFzdGVyXVxuICAgIFxuICAgIGZsYWcgLS0-IHxOb3wgQmxvY2tcbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)

**CI work** is a must job.
**Who** could be us or **CI**.

**Comment by jjw24** [comment]
yep looks good

**Comment by Zeroto521** [comment]
about the checking content.

I think we can only check one thing is the `ID`.

If check the `Url`, there may have some network problems.

**Comment by jjw24** [comment]
yeah no need to check url. ID, Language and correct format eg. correct json format spacing (if possible), correct commas  and "" are closed off.
