### ISSUE TITLE
Remove the Google Calendar plugin

### ISSUE THREAD

**Issue by ivanipenburg** [Flow-Launcher/Flow.Launcher.PluginsManifest#322]
Hi,

I'm the author of the [Google Calendar plugin](https://github.com/ivanipenburg/Flow.Launcher.Plugin.GoogleCalendar). I think the plugin got broken after the upgrade to the new Python version and sadly I didn't manage to fix it then and don't have the time now. Can the plugin be removed, then people won't download a broken plugin.

Thanks in advance.

**Comment by jjw24** [comment]
Hey no worries. Keep the repo around so whoever would like could continue to build on it.
