### ISSUE TITLE
Updating Plugins

### ISSUE THREAD

**Issue by HorridModz** [Flow-Launcher/Flow.Launcher.PluginsManifest#370]
I've made a major update to my [plugin](https://github.com/HorridModz/Flow.Launcher.Plugin.Add2Path), which adds features and fixes bugs. Is there a way to roll out the update? If I submit a pull request to overwrite it in [plugins.json](https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/blob/plugin_api_v2/plugins.json), will it automatically update? Or is there a way to notify users of my plugin and give them an option to update it?

Thanks.

**Comment by HorridModz** [comment]
Also, my plugin's `UrlDownload` is listed as `https://github.com/HorridModz/Flow.Launcher.Plugin.Add2Path/releases/download/v1.0.0/Flow.Launcher.Plugin.Add2Path.zip`, but in my new release (2.0.0) the link has changed to `https://github.com/HorridModz/Flow.Launcher.Plugin.Add2Path/releases/download/v2.0.0/Flow.Launcher.Plugin.Add2Path.zip`.  So I assume this will break the CI?

**Comment by NoPlagiarism** [comment]
> Is there a way to roll out the update?

Just use GitHub release, preferable using workflow like [this one](https://github.com/taooceros/Flow.Plugin.WindowWalker/blob/master/.github/workflows/publish-action.yml)

> will it automatically update

It automatically updates using data from repo releases. It already did [ https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/commit/bff84b3af7f186be71436a983b66f82d970f3063 ]

> is there a way to notify users of my plugin

1. `pm update`
2. There is Discord channel which has notification about every plugin included in this manifest

**Comment by HorridModz** [comment]
> > Is there a way to roll out the update?
> 
> Just use GitHub release, preferable using workflow like [this one](https://github.com/taooceros/Flow.Plugin.WindowWalker/blob/master/.github/workflows/publish-action.yml?rgh-link-date=2024-07-31T21%3A37%3A56Z)
> 
> > will it automatically update
> 
> It automatically updates using data from repo releases. It already did ( [bff84b3](https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/commit/bff84b3af7f186be71436a983b66f82d970f3063) )
> 
> > is there a way to notify users of my plugin
> 
> 1. `pm update`
> 2. There is Discord channel which has notification about every plugin included in this manifest

It already updated? That's interesting, how would it know if the release link changed (or it just uses latest release)? But I see the commit you linked - thanks for letting me know.

**Comment by HorridModz** [comment]
I thought I already posted this, but I don't see it so I'll post it again - it doesn't seem to have updated on my end. I both reinstalled the plugin and ran `pm update`; it's still using the old version in my FlowLauncher.

**Comment by HorridModz** [comment]
@jjw24

**Comment by jjw24** [comment]
So all plugins do get updated to newer versions automatically, it's an automated process that checks for new versions. You don't need to submit a separate pr after you release an update to your plugin as long as it's using GitHub Release as mentioned by NoPlagiarism.

The availability in the Plugin Store after the manifest is updated may vary because of the use of CDN and their caching policy, but will appear in the store eventually.

**Comment by jjw24** [comment]
@HorridModz I see your plugin repo does not use  GitHub Action workflow to publish your release, please add it. You can follow [this](https://github.com/taooceros/Flow.Plugin.WindowWalker/blob/master/.github/workflows/publish-action.yml) to add it.

Please ensure the workflow is added as it is an important requirement for all plugins in the store.

**Comment by HorridModz** [comment]
> @HorridModz I see your plugin repo does not use GitHub Action workflow to publish your release, please add it. You can follow [this](https://github.com/taooceros/Flow.Plugin.WindowWalker/blob/master/.github/workflows/publish-action.yml?rgh-link-date=2024-08-03T05%3A25%3A08Z) as an example.
> 
> Please ensure the workflow is added as it is an important requirement for all plugins in the store.

Sorry for being a stubborn pain in the butt, but I've never used Github Actions. Do I have to - this is just a wild case - add that file to my project and edit it, and then it will run and everything will somehow be unicorns and rainbows next time I push to Github? Is there a tutorial or some guide I can follow? Thanks, and sorry for asking you to spoonfeed me.

**Comment by HorridModz** [comment]
> The availability in the Plugin Store after the manifest is updated may vary because of the use of CDN and their caching policy, but will appear in the store eventually.

Oh wow, I tried `pm update` again and it worked this time! That's great! It kind of sucks that the update isn't automatically rolled out, though, as major bugfixes are included that fix corruption of the `PATH` environmental variable (a serious change I want people to automatically have) - would it have been considered the plugin's responsible to detect and require updates when it was first written and published?

**Comment by jjw24** [comment]
> > @HorridModz I see your plugin repo does not use GitHub Action workflow to publish your release, please add it. You can follow [this](https://github.com/taooceros/Flow.Plugin.WindowWalker/blob/master/.github/workflows/publish-action.yml?rgh-link-date=2024-08-03T05%3A25%3A08Z) as an example.
> > Please ensure the workflow is added as it is an important requirement for all plugins in the store.
> 
> Sorry for being a stubborn pain in the butt, but I've never used Github Actions. Do I have to - this is just a wild case - add that file to my project and edit it, and then it will run and everything will somehow be unicorns and rainbows next time I push to Github? Is there a tutorial or some guide I can follow? Thanks, and sorry for asking you to spoonfeed me.

All good.

GitHub Actions is a CI/CD (Continuous Integration and Continuous Deployment) platform that allows you to automate your project development workflows. It enables you to build, test, and release your code (plugin in your case) directly from GitHub by creating custom workflows defined in YAML files. These workflows can be triggered by various events, such as push events, pull requests, or schedule-based triggers, so when you push your code changes it will build it automatically, and when you push your code into your main branch, it will automatically create a new GitHub Release. This means you do not need to build locally on your computer, zip up the files and manually create a release.

Give that file a go, do it on a separate branch, and when I have some free time I can help you fix any issues you may have with it. You can try this https://docs.github.com/en/actions/using-workflows/about-workflows#create-an-example-workflow

**Comment by HorridModz** [comment]
> > > @HorridModz I see your plugin repo does not use GitHub Action workflow to publish your release, please add it. You can follow [this](https://github.com/taooceros/Flow.Plugin.WindowWalker/blob/master/.github/workflows/publish-action.yml?rgh-link-date=2024-08-04T10%3A00%3A32Z) as an example.
> > > Please ensure the workflow is added as it is an important requirement for all plugins in the store.
> > 
> > 
> > Sorry for being a stubborn pain in the butt, but I've never used Github Actions. Do I have to - this is just a wild case - add that file to my project and edit it, and then it will run and everything will somehow be unicorns and rainbows next time I push to Github? Is there a tutorial or some guide I can follow? Thanks, and sorry for asking you to spoonfeed me.
> 
> All good.
> 
> GitHub Actions is a CI/CD (Continuous Integration and Continuous Deployment) platform that allows you to automate your project development workflows. It enables you to build, test, and release your code (plugin in your case) directly from GitHub by creating custom workflows defined in YAML files. These workflows can be triggered by various events, such as push events, pull requests, or schedule-based triggers, so when you push your code changes it will build it automatically, and when you push your code into your main branch, it will automatically create a new GitHub Release. This means you do not need to build locally on your computer, zip up the files and manually create a release.
> 
> Give that file a go, do it on a separate branch, and when I have some free time I can help you fix any issues you may have with it. You can try this [docs.github.com/en/actions/using-workflows/about-workflows#create-an-example-workflow](https://docs.github.com/en/actions/using-workflows/about-workflows#create-an-example-workflow)

Thank you! Sounds good.

**Comment by HorridModz** [comment]
> > > @HorridModz I see your plugin repo does not use GitHub Action workflow to publish your release, please add it. You can follow [this](https://github.com/taooceros/Flow.Plugin.WindowWalker/blob/master/.github/workflows/publish-action.yml?rgh-link-date=2024-08-04T10%3A00%3A32Z) as an example.
> > > Please ensure the workflow is added as it is an important requirement for all plugins in the store.
> > 
> > 
> > Sorry for being a stubborn pain in the butt, but I've never used Github Actions. Do I have to - this is just a wild case - add that file to my project and edit it, and then it will run and everything will somehow be unicorns and rainbows next time I push to Github? Is there a tutorial or some guide I can follow? Thanks, and sorry for asking you to spoonfeed me.
> 
> All good.
> 
> GitHub Actions is a CI/CD (Continuous Integration and Continuous Deployment) platform that allows you to automate your project development workflows. It enables you to build, test, and release your code (plugin in your case) directly from GitHub by creating custom workflows defined in YAML files. These workflows can be triggered by various events, such as push events, pull requests, or schedule-based triggers, so when you push your code changes it will build it automatically, and when you push your code into your main branch, it will automatically create a new GitHub Release. This means you do not need to build locally on your computer, zip up the files and manually create a release.
> 
> Give that file a go, do it on a separate branch, and when I have some free time I can help you fix any issues you may have with it. You can try this [docs.github.com/en/actions/using-workflows/about-workflows#create-an-example-workflow](https://docs.github.com/en/actions/using-workflows/about-workflows#create-an-example-workflow)

Just one more question, if you don't mind. Should I create the action files locally, or on the remote repository? Does it matter?

**Comment by HorridModz** [comment]
@jjw24 If you're able to, it would be great if you could check out the [pull request](https://github.com/HorridModz/Flow.Launcher.Plugin.Add2Path/pull/4) I just created in my plugin's repo. Absolutely no rush, and I really appreciate all the help.

I'll close this issue since it has nothing to do with this repository and we should be good to go,
