### ISSUE TITLE
Update etag only when it doesn't exist

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher.PluginsManifest#38]
Change to update etag only when it doesn't exist ie a new plugin. It seems from the commits etag changes every now or so.

**Comment by taooceros** [comment]
We need to update that or else the check for etag won't work (only exact same etag means nothing has been updated). I think github is automatically updating the e-tag every day or every few days.

**Comment by jjw24** [comment]
Do we need to update the etag our end as well? Would it be possible to ignore the new etag until when we need to update the version?

**Comment by taooceros** [comment]
We still need to update that. I originally think that it will only change when new release appears, but now it seems will automatically update in a period, so we need to keep the latest e-tag to request 304 instead of the actual release page.

**Comment by jjw24** [comment]
What would happen if the etag is not the latest do you know? Is it just going to fail or will it return a new one still

**Comment by taooceros** [comment]
> What would happen if the etag is not the latest do you know? Is it just going to fail or will it return a new one still

Yeah, but that will return the whole page so that it will still count toward the resource limit, and that will make the e-tag without usage.
