### ISSUE TITLE
Using Github Release to automatically check newest release

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher.PluginsManifest#4]
I think we can follow the way `Updater.cs` checking the newest update for Flow to automatically get the newest update for plugins instead of storing the direct download link in plugin.json.
This can avoid updating pluginsmanifest every time plugins update. Or checking the update is also part of the review process?

**Comment by taooceros** [comment]
https://github.com/Flow-Launcher/Flow.Launcher/blob/f714e1e4e01b6640c4b8dbcf66ca6ec94dd5cb5b/Flow.Launcher.Core/Updater.cs#L131-L148

**Comment by taooceros** [comment]
Here are some idea.
1. Remove the version number in plugin.json, since it will not be updated here.
2. Add JsonDeserilization in PluginManager like what has done in Updater.cs.
3. Only add the project url in pluginmanifest instead of the direct downloadurl.

**Comment by jjw24** [comment]
> I think we can follow the way `Updater.cs` checking the newest update for Flow to automatically get the newest update for plugins instead of storing the direct download link in plugin.json.
> This can avoid updating pluginsmanifest every time plugins update. Or checking the update is also part of the review process?

hmm the reason i included version is so we dont have a scenario where malicious actor creates a plugin, gets approved, then uploads another zip file, and our code just looks for the latest and updates user's plugin to the malicious new release. At lease we can say on the day of our approval, we approved this version as at this date, any subsequent uploads to the same version we will not be able to be responsible. If we just approve the plugin once, subsequent uploads we won't know about.

What do you think?

**Comment by jjw24** [comment]
> Only add the project url in pluginmanifest instead of the direct downloadurl.

Project url/website, code url and direct download url are separated in the case where people may decide to have a website for the plugin different to where the code lives, eg GitLab

**Comment by taooceros** [comment]
> > Only add the project url in pluginmanifest instead of the direct downloadurl.
> 
> Project url/website, code url and direct download url are separated in the case where people may decide to have a website for the plugin different to where the code lives, eg GitLab

You are right, but manually pr every update may be quite significant works when Plugins become more... Maybe we can provide different way of doing that. By providing direct url, we won't support auto update, while we can support auto update for github or gitlab.

**Comment by taooceros** [comment]
Maybe we can use CI to automatically check for new update, and update the file.
